# This file is located in /frontend, so all paths are relative to it.

[build]
  command = "npm run build"
  publish = "dist"
  # We do NOT set a "base" directory here, because Netlify's
  # UI setting will handle that.

[[redirects]]
  from = "/api/*"
  to = "https://ecocartplus-backend.onrender.com/api/:splat"
  status = 200